#!/usr/bin/perl -w
use strict;
use FileHandle;
use IO::Pipe;
use lib 'blib/lib';
use Catalyst::Test 'ZenAH';

$ENV{TEST_HARNESS} = 1; # pretend to be test harness

my $file = shift;
my $req = shift;

if (-f $file) {
  die $file." already exists" if (defined $req);
  my $fh = FileHandle->new($file);
  $req = <$fh>;
  chomp $req;
  $fh->close;
}

my $resp = request($req);
my $content = $resp->content;
$content =~ s/\n\s*\n/\n/mg;
$content =~ s/\s+\n$/\n/mg;
my $fh = FileHandle->new('>'.$file);
my $ct = $resp->content_type;
$ct =~ s/charset=utf-8$//;
print $fh $req, "\n", $ct, "\n", $resp->status_line, "\n\n";
if ($resp->code == '303') {
  print $fh $resp->location,"\n";
} else {
  print $fh $content;
}

$fh->close or die "$file close error: $!\n";
